name: deployToAzure
on:
  workflow_call:
    inputs:
      azureWebAppName:
        required: true
        type: string
      packageName:
        required: true
        type: string
      environmentName:
        required: true
        type: string
    secrets:
      azurePublishProfile:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download All artifacts
      uses: actions/download-artifact@v2

    - name: Run Azure webapp deploy to ${{ inputs.environmentName }} using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.azurePublishProfile }} # Define secret variable in repository settings as per action documentation
        package: ${{ inputs.packageName }}